=== daniwlmesa12/XSD/XmlRESTfulNodeJSfromJS-master/api/xsd/localidades.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="direccion" type="xs:string"/>
    <xs:element name="velocidad" type="xs:string"/>
    <xs:element name="maxima" type="xs:byte"/>
    <xs:element name="minima" type="xs:byte"/>
    <xs:element name="dato">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="hora" type="xs:byte" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="prob_precipitacion">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="periodo" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="cota_nieve_prov">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="periodo" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="estado_cielo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="periodo" type="xs:string" use="optional"/>
                    <xs:attribute name="descripcion" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="viento">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="direccion"/>
                <xs:element ref="velocidad"/>
            </xs:sequence>
            <xs:attribute name="periodo" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="racha_max">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="periodo" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="temperatura">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="maxima"/>
                <xs:element ref="minima"/>
                <xs:element ref="dato" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sens_termica">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="maxima"/>
                <xs:element ref="minima"/>
                <xs:element ref="dato" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="humedad_relativa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="maxima"/>
                <xs:element ref="minima"/>
                <xs:element ref="dato" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="uv_max" type="xs:string"/>
    <xs:element name="dia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="prob_precipitacion" maxOccurs="unbounded"/>
                <xs:element ref="cota_nieve_prov" maxOccurs="unbounded"/>
                <xs:element ref="estado_cielo" maxOccurs="unbounded"/>
                <xs:element ref="viento" maxOccurs="unbounded"/>
                <xs:element ref="racha_max" maxOccurs="unbounded"/>
                <xs:element ref="temperatura"/>
                <xs:element ref="sens_termica"/>
                <xs:element ref="humedad_relativa"/>
                <xs:element ref="uv_max" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="elaborado" type="xs:dateTime"/>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="provincia" type="xs:string"/>
    <xs:element name="prediccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dia" maxOccurs="7"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="productor" type="xs:string"/>
    <xs:element name="web" type="xs:string"/>
    <xs:element name="enlace" type="xs:string"/>
    <xs:element name="language" type="xs:string"/>
    <xs:element name="copyright" type="xs:string"/>
    <xs:element name="nota_legal" type="xs:string"/>
    <xs:element name="origen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="productor"/>
                <xs:element ref="web"/>
                <xs:element ref="enlace"/>
                <xs:element ref="language"/>
                <xs:element ref="copyright"/>
                <xs:element ref="nota_legal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="origen"/>
                <xs:element ref="elaborado"/>
                <xs:element ref="nombre"/>
                <xs:element ref="provincia"/>
                <xs:element ref="prediccion"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="version" type="xs:float"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daniwlmesa12/XSD/XmlRESTfulNodeJSfromJS-master/api/xml/tiempo.xml
<root xmlns:xsd="https://www.w3.org/2001/XMLSchema"
    xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" id="28079" version="1.0" xsi:noNamespaceSchemaLocation="api\xsd\localidades.xsd">
    <origen>
        <productor>Agencia Estatal de Meteorología - AEMET. Gobierno de España</productor>
        <web>https://www.aemet.es</web>
        <enlace>https://www.aemet.es/es/eltiempo/prediccion/municipios/madrid-id28079</enlace>
        <language>es</language>
        <copyright>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.</copyright>
        <nota_legal>https://www.aemet.es/es/nota_legal</nota_legal>
    </origen>
    <elaborado>2023-01-26T13:47:45</elaborado>
    <nombre>Madrid</nombre>
    <provincia>Madrid</provincia>
    <prediccion>
        <dia fecha="2023-01-26">
            <prob_precipitacion periodo="00-24"/>
            <prob_precipitacion periodo="00-12"/>
            <prob_precipitacion periodo="12-24">0</prob_precipitacion>
            <prob_precipitacion periodo="00-06"/>
            <prob_precipitacion periodo="06-12">0</prob_precipitacion>
            <prob_precipitacion periodo="12-18">0</prob_precipitacion>
            <prob_precipitacion periodo="18-24">0</prob_precipitacion>
            <cota_nieve_prov periodo="00-24"/>
            <cota_nieve_prov periodo="00-12"/>
            <cota_nieve_prov periodo="12-24"/>
            <cota_nieve_prov periodo="00-06"/>
            <cota_nieve_prov periodo="06-12"/>
            <cota_nieve_prov periodo="12-18"/>
            <cota_nieve_prov periodo="18-24"/>
            <estado_cielo periodo="00-24" descripcion=""/>
            <estado_cielo periodo="00-12" descripcion=""/>
            <estado_cielo periodo="12-24" descripcion="Poco nuboso">12</estado_cielo>
            <estado_cielo periodo="00-06" descripcion=""/>
            <estado_cielo periodo="06-12" descripcion="Poco nuboso">12</estado_cielo>
            <estado_cielo periodo="12-18" descripcion="Poco nuboso">12</estado_cielo>
            <estado_cielo periodo="18-24" descripcion="Despejado">11n</estado_cielo>
            <viento periodo="00-24">
                <direccion/>
                <velocidad/>
            </viento>
            <viento periodo="00-12">
                <direccion/>
                <velocidad/>
            </viento>
            <viento periodo="12-24">
                <direccion>NE</direccion>
                <velocidad>20</velocidad>
            </viento>
            <viento periodo="00-06">
                <direccion>C</direccion>
                <velocidad>0</velocidad>
            </viento>
            <viento periodo="06-12">
                <direccion>NO</direccion>
                <velocidad>10</velocidad>
            </viento>
            <viento periodo="12-18">
                <direccion>NE</direccion>
                <velocidad>20</velocidad>
            </viento>
            <viento periodo="18-24">
                <direccion>N</direccion>
                <velocidad>10</velocidad>
            </viento>
            <racha_max periodo="00-24"/>
            <racha_max periodo="00-12"/>
            <racha_max periodo="12-24"/>
            <racha_max periodo="00-06"/>
            <racha_max periodo="06-12"/>
            <racha_max periodo="12-18"/>
            <racha_max periodo="18-24"/>
            <temperatura>
                <maxima>8</maxima>
                <minima>2</minima>
                <dato hora="06">4</dato>
                <dato hora="12">7</dato>
                <dato hora="18">6</dato>
                <dato hora="24">3</dato>
            </temperatura>
            <sens_termica>
                <maxima>9</maxima>
                <minima>2</minima>
                <dato hora="06">4</dato>
                <dato hora="12">5</dato>
                <dato hora="18">3</dato>
                <dato hora="24">0</dato>
            </sens_termica>
            <humedad_relativa>
                <maxima>70</maxima>
                <minima>50</minima>
                <dato hora="06">55</dato>
                <dato hora="12">50</dato>
                <dato hora="18">55</dato>
                <dato hora="24">70</dato>
            </humedad_relativa>
            <uv_max>1</uv_max>
        </dia>
        <dia fecha="2023-01-27">
            <prob_precipitacion periodo="00-24">0</prob_precipitacion>
            <prob_precipitacion periodo="00-12">0</prob_precipitacion>
            <prob_precipitacion periodo="12-24">0</prob_precipitacion>
            <prob_precipitacion periodo="00-06">0</prob_precipitacion>
            <prob_precipitacion periodo="06-12">0</prob_precipitacion>
            <prob_precipitacion periodo="12-18">0</prob_precipitacion>
            <prob_precipitacion periodo="18-24">0</prob_precipitacion>
            <cota_nieve_prov periodo="00-24"/>
            <cota_nieve_prov periodo="00-12"/>
            <cota_nieve_prov periodo="12-24"/>
            <cota_nieve_prov periodo="00-06"/>
            <cota_nieve_prov periodo="06-12"/>
            <cota_nieve_prov periodo="12-18"/>
            <cota_nieve_prov periodo="18-24"/>
            <estado_cielo periodo="00-24" descripcion="Despejado">11</estado_cielo>
            <estado_cielo periodo="00-12" descripcion="Despejado">11</estado_cielo>
            <estado_cielo periodo="12-24" descripcion="Despejado">11</estado_cielo>
            <estado_cielo periodo="00-06" descripcion="Despejado">11n</estado_cielo>
            <estado_cielo periodo="06-12" descripcion="Despejado">11</estado_cielo>
            <estado_cielo periodo="12-18" descripcion="Despejado">11</estado_cielo>
            <estado_cielo periodo="18-24" descripcion="Despejado">11n</estado_cielo>
            <viento periodo="00-24">
                <direccion>N</direccion>
                <velocidad>25</velocidad>
            </viento>
            <viento periodo="00-12">
                <direccion>N</direccion>
                <velocidad>25</velocidad>
            </viento>
            <viento periodo="12-24">
                <direccion>N</direccion>
                <velocidad>25</velocidad>
            </viento>
            <viento periodo="00-06">
                <direccion>C</direccion>
                <velocidad>0</velocidad>
            </viento>
            <viento periodo="06-12">
                <direccion>N</direccion>
                <velocidad>25</velocidad>
            </viento>
            <viento periodo="12-18">
                <direccion>N</direccion>
                <velocidad>25</velocidad>
            </viento>
            <viento periodo="18-24">
                <direccion>N</direccion>
                <velocidad>15</velocidad>
            </viento>
            <racha_max periodo="00-24">45</racha_max>
            <racha_max periodo="00-12">45</racha_max>
            <racha_max periodo="12-24">45</racha_max>
            <racha_max periodo="00-06"/>
            <racha_max periodo="06-12">45</racha_max>
            <racha_max periodo="12-18">40</racha_max>
            <racha_max periodo="18-24"/>
            <temperatura>
                <maxima>9</maxima>
                <minima>0</minima>
                <dato hora="06">4</dato>
                <dato hora="12">8</dato>
                <dato hora="18">6</dato>
                <dato hora="24">3</dato>
            </temperatura>
            <sens_termica>
                <maxima>5</maxima>
                <minima>-2</minima>
                <dato hora="06">4</dato>
                <dato hora="12">4</dato>
                <dato hora="18">2</dato>
                <dato hora="24">-1</dato>
            </sens_termica>
            <humedad_relativa>
                <maxima>70</maxima>
                <minima>40</minima>
                <dato hora="06">55</dato>
                <dato hora="12">45</dato>
                <dato hora="18">50</dato>
                <dato hora="24">55</dato>
            </humedad_relativa>
            <uv_max>2</uv_max>
        </dia>
        <dia fecha="2023-01-28">
            <prob_precipitacion periodo="00-24">0</prob_precipitacion>
            <prob_precipitacion periodo="00-12">0</prob_precipitacion>
            <prob_precipitacion periodo="12-24">0</prob_precipitacion>
            <cota_nieve_prov periodo="00-24"/>
            <cota_nieve_prov periodo="00-12"/>
            <cota_nieve_prov periodo="12-24"/>
            <estado_cielo periodo="00-24" descripcion="Poco nuboso">12</estado_cielo>
            <estado_cielo periodo="00-12" descripcion="Poco nuboso">12</estado_cielo>
            <estado_cielo periodo="12-24" descripcion="Poco nuboso">12</estado_cielo>
            <viento periodo="00-24">
                <direccion>NE</direccion>
                <velocidad>20</velocidad>
            </viento>
            <viento periodo="00-12">
                <direccion>NE</direccion>
                <velocidad>20</velocidad>
            </viento>
            <viento periodo="12-24">
                <direccion>NE</direccion>
                <velocidad>20</velocidad>
            </viento>
            <racha_max periodo="00-24">40</racha_max>
            <racha_max periodo="00-12">40</racha_max>
            <racha_max periodo="12-24">40</racha_max>
            <temperatura>
                <maxima>8</maxima>
                <minima>-1</minima>
            </temperatura>
            <sens_termica>
                <maxima>8</maxima>
                <minima>1</minima>
            </sens_termica>
            <humedad_relativa>
                <maxima>65</maxima>
                <minima>40</minima>
            </humedad_relativa>
            <uv_max>2</uv_max>
        </dia>
        <dia fecha="2023-01-29">
            <prob_precipitacion periodo="00-24">0</prob_precipitacion>
